FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Запускаем Celery Beat (планировщик)
CMD ["celery", "-A", "celery_app", "beat", "--loglevel=info"]