"""Add_channels_templates_giveaways

Revision ID: 3ba89ddc3c43
Revises: faab144d4c68
Create Date: 2026-03-15 15:40:04.017499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba89ddc3c43'
down_revision: Union[str, Sequence[str], None] = 'faab144d4c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_telegram_id'), 'channels', ['telegram_id'], unique=True)
    op.create_table('post_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('button_text', sa.String(length=100), nullable=False),
    sa.Column('button_color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('giveaways', sa.Column('template_id', sa.Integer(), nullable=False))
    op.add_column('giveaways', sa.Column('giveaway_type', sa.Enum('STANDARD', 'BOOSTS', 'INVITES', 'CUSTOM', name='giveawaytype', native_enum=False, length=50), nullable=False))
    op.add_column('giveaways', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('giveaways', sa.Column('use_captcha', sa.Boolean(), nullable=False))
    op.add_column('giveaways', sa.Column('allow_stories', sa.Boolean(), nullable=False))
    op.add_column('giveaways', sa.Column('max_invites', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'giveaways', 'post_templates', ['template_id'], ['id'])
    op.drop_column('giveaways', 'created_at')
    op.drop_column('giveaways', 'description')
    op.drop_constraint(op.f('users_invited_by_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'invited_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_invited_by_fkey'), 'users', 'users', ['invited_by'], ['telegram_id'])
    op.add_column('giveaways', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('giveaways', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'giveaways', type_='foreignkey')
    op.drop_column('giveaways', 'max_invites')
    op.drop_column('giveaways', 'allow_stories')
    op.drop_column('giveaways', 'use_captcha')
    op.drop_column('giveaways', 'start_date')
    op.drop_column('giveaways', 'giveaway_type')
    op.drop_column('giveaways', 'template_id')
    op.drop_table('post_templates')
    op.drop_index(op.f('ix_channels_telegram_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
