"""giveaways_v2

Revision ID: ba41ddde8ba7
Revises: 7383aa927e04
Create Date: 2026-03-24 19:54:32.820185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba41ddde8ba7'
down_revision: Union[str, Sequence[str], None] = '7383aa927e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('button_text', sa.String(length=100), nullable=False))
    op.add_column('giveaways', sa.Column('button_color_emoji', sa.String(length=10), nullable=False))
    op.add_column('giveaways', sa.Column('sponsor_channel_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False))
    op.add_column('giveaways', sa.Column('publish_channel_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False))
    op.add_column('giveaways', sa.Column('result_channel_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False))
    op.add_column('giveaways', sa.Column('start_immediately', sa.Boolean(), nullable=False))
    op.add_column('giveaways', sa.Column('use_boosts', sa.Boolean(), nullable=False))
    op.add_column('giveaways', sa.Column('use_invites', sa.Boolean(), nullable=False))
    op.add_column('giveaways', sa.Column('use_stories', sa.Boolean(), nullable=False))
    op.add_column('giveaways', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_column('giveaways', 'giveaway_type')
    op.drop_column('giveaways', 'allow_stories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('allow_stories', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('giveaways', sa.Column('giveaway_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('giveaways', 'status')
    op.drop_column('giveaways', 'use_stories')
    op.drop_column('giveaways', 'use_invites')
    op.drop_column('giveaways', 'use_boosts')
    op.drop_column('giveaways', 'start_immediately')
    op.drop_column('giveaways', 'result_channel_ids')
    op.drop_column('giveaways', 'publish_channel_ids')
    op.drop_column('giveaways', 'sponsor_channel_ids')
    op.drop_column('giveaways', 'button_color_emoji')
    op.drop_column('giveaways', 'button_text')
    # ### end Alembic commands ###