"""add_button_color_and_custom_emoji

Revision ID: 061a8898ba17
Revises: 5a31f08eb5d0
Create Date: 2026-04-04 01:30:49.393049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061a8898ba17'
down_revision: Union[str, Sequence[str], None] = '5a31f08eb5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('button_custom_emoji_id', sa.String(length=50), nullable=True))
    op.drop_column('giveaways', 'button_emoji_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('button_emoji_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('giveaways', 'button_custom_emoji_id')
    # ### end Alembic commands ###
