"""add_boost_channels_and_boost_count

Revision ID: 06209af63406
Revises: 061a8898ba17
Create Date: 2026-04-05 23:24:57.581135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06209af63406'
down_revision: Union[str, Sequence[str], None] = '061a8898ba17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('boost_channel_ids', postgresql.ARRAY(sa.BigInteger()), server_default='{}', nullable=False))
    op.add_column('participants', sa.Column('boost_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'boost_count')
    op.drop_column('giveaways', 'boost_channel_ids')
    # ### end Alembic commands ###