"""add_participant_flags

Revision ID: 48155a2ab291
Revises: 79545805f81a
Create Date: 2026-03-27 23:59:38.243781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48155a2ab291'
down_revision: Union[str, Sequence[str], None] = '79545805f81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Добавляем is_active. Старые участники считаются активными (true)
    op.add_column('participants', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    
    # СТРОКУ С is_winner МЫ УДАЛИЛИ, ПОТОМУ ЧТО ОНА УЖЕ ЕСТЬ В БАЗЕ!
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'is_active')
    # СТРОКУ С is_winner МЫ УДАЛИЛИ
    # ### end Alembic commands ###