"""add_button_color

Revision ID: 5a31f08eb5d0
Revises: 48155a2ab291
Create Date: 2026-04-04 00:11:24.339494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a31f08eb5d0'
down_revision: Union[str, Sequence[str], None] = '48155a2ab291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('button_color', sa.String(length=20), server_default='default', nullable=False))
    op.add_column('giveaways', sa.Column('button_emoji_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaways', 'button_emoji_id')
    op.drop_column('giveaways', 'button_color')
    # ### end Alembic commands ###