"""sdsdsdd99

Revision ID: 88fc0d5bdf49
Revises: b87a9838902b
Create Date: 2026-04-08 21:04:00.176597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fc0d5bdf49'
down_revision: Union[str, Sequence[str], None] = 'b87a9838902b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('post_message_id', sa.Integer(), nullable=True))
    op.add_column('giveaways', sa.Column('post_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaways', 'post_channel_id')
    op.drop_column('giveaways', 'post_message_id')
    # ### end Alembic commands ###
