"""add_mascot_id_remove_stories

Revision ID: b87a9838902b
Revises: 06209af63406
Create Date: 2026-04-06 20:27:40.419027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87a9838902b'
down_revision: Union[str, Sequence[str], None] = '06209af63406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('mascot_id', sa.String(length=20), server_default='1-duck', nullable=False))
    op.drop_column('giveaways', 'use_stories')
    op.drop_column('participants', 'story_clicks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('story_clicks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('giveaways', sa.Column('use_stories', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('giveaways', 'mascot_id')
    # ### end Alembic commands ###
